name: Build CI

on: [ push, pull_request ]

env:
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

jobs:
    build:

        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
                python-version: [ 3.8, 3.9, '3.10', '3.11' ]
                exclude:
                    - os: windows-latest
                      python-version: '3.11'

        env:
            DISPLAY: ':99.0'
        steps:
            -   name: Get repository
                uses: actions/checkout@v3
            -   name: apt-get update (Linux)
                if: runner.os == 'Linux'
                run: sudo apt-get update
            -   name: Setup Qt requirements for Linux
                uses: tlambert03/setup-qt-libs@v1
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade -r requirements_dev.txt
                    python -m pip install .
            -   name: Test with pytest
                run: |
                    pytest tests/
                continue-on-error: false

